name: monthly LTS check

on:
  schedule:
    # 7pm UTC, 15th of every month
    # Scheduled to hopefully be during TTS business days most of the time
    - cron: '0 19 15 * *'

jobs:
  lts-check:
    name: current LTS check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 18
      
      - run: node lts.js
