name: test and lint

on: 
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: lint
        run: npm run lint

  format:
    name: verify formatting
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: verify formatting
        run: npm run format-test

  test:
    name: unit tests
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: run tests
        run: npm test
